security:
  oauth2:
    resource:
      userInfoUri: https://apptime.us-east-1.amazoncognito.com/oauth2/userInfo
      tokenInfoUri: https://apptime.us-east-1.amazoncognito.com/oauth2/token
      jwk:
        key-set-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_TonoYZaSY/.well-known/jwks.json
    client:
      clientId: 34osghte5cfsg8iktmilk6gbg0
---
spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      enabled: true
    path: /h2
server:
  port: 8001
predictionEngineHost: http://localhost:5000
---
spring:
  profiles: aws
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://aa4gunc5mrmbny.cfbbfychwenn.us-east-2.rds.amazonaws.com:5432/ebdb
    username: authdb
    password: password
    driverClassName: org.postgresql.Driver
server:
  port: 5000
predictionEngineHost: http://ec2-52-91-41-42.compute-1.amazonaws.com:5000 
---
spring:
  profiles: postgre
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/authdb
    username: authdb
    password: password
    driverClassName: org.postgresql.Driver
server:
  port: 8001
predictionEngineHost: http://localhost:5000 # will be updated later
